import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import ToastProvider from "./providers/ToastProvider";
import StyledComponentsRegistry from './providers/AntdRegistry';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Project Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <StyledComponentsRegistry>
          <div id="root">
            {children}
            <ToastProvider />
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
